### ISSUE TITLE
Please clarify software license for mockJSON

### ISSUE THREAD

**Issue by ryansmith111** [mennovanslooten/mockJSON#6]
I like your mockJSON library, and I would like to use it, but no license is specified with the code. 
In many countries, this means that others have _no right to use the code_.
Please specify a license in the code, in the readme, on the website, or in a LICENSE file in the project source.
Preferably an MIT or BSD license. For example, http://en.wikipedia.org/wiki/MIT_License/

Thanks!

**Comment by mennovanslooten** [comment]
Done!

**Comment by ryansmith111** [comment]
Awesome - thanks!!

On Wed, Mar 21, 2012 at 6:58 PM, Menno van Slooten <
reply@reply.github.com
